// ============================================================
// SOUL.md 同步 — 定期从 Norma 拉取人格状态
// 写入 OpenClaw workspace 的 SOUL.md，让 AI 感知当前人格
// ============================================================

import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { homedir } from 'node:os';

const PERSONA_API = `http://127.0.0.1:${process.env.PERSONA_HTTP_PORT || '19820'}`;
const SOUL_PATH = resolve(homedir(), '.openclaw', 'workspace', 'SOUL.md');

const SOUL_HEADER = `<!-- AUTO-GENERATED by Norma — DO NOT EDIT MANUALLY -->
<!-- This file is periodically synced from the persona engine -->

`;

/**
 * 从 Norma HTTP API 拉取当前人格状态，写入 SOUL.md
 */
export async function syncSoulMd(): Promise<boolean> {
  try {
    const res = await fetch(`${PERSONA_API}/api/state?format=prompt`, {
      signal: AbortSignal.timeout(3000),
    });
    if (!res.ok) return false;

    const personaText = await res.text();
    const content = SOUL_HEADER + personaText + '\n';

    // 只在内容变化时写入
    if (existsSync(SOUL_PATH)) {
      const existing = readFileSync(SOUL_PATH, 'utf-8');
      if (existing === content) return true;
    }

    writeFileSync(SOUL_PATH, content, 'utf-8');
    return true;
  } catch {
    return false;
  }
}

/**
 * 启动定期同步（每 60 秒）
 */
export function startSoulSync(intervalMs: number = 60_000): NodeJS.Timeout {
  // 立即同步一次
  syncSoulMd();
  return setInterval(syncSoulMd, intervalMs);
}
